### ISSUE TITLE
aerospike is in init state

### ISSUE THREAD

**Issue by Asisranjan** [aerospike/aerospike-kubernetes-enterprise#15]
helm install is successful with featureKeyFilePath. but the pods are in init state
root@ddeVM(~)$ kubectl get pods
NAME                                       READY   STATUS     RESTARTS   AGE
aerospike-release-aerospike-enterprise-0   0/1     Init:0/1   0          13m

**Comment by spkesan** [comment]
Hi @Asisranjan
Is it stuck at INIT state?
Can you share the output of `kubectl describe pod/aerospike-release-aerospike-enterprise-0` and `kubectl logs pod/aerospike-release-aerospike-enterprise-0 -c aerospike-init`

**Comment by spkesan** [comment]
@Asisranjan 
I wonder if it's related to the internet connectivity issue.
We have some improvements in the [latest release](https://github.com/aerospike/aerospike-kubernetes-enterprise/releases/tag/1.2.0) where we made necessary scripts and utils as part of our init container image and it no longer connects to the internet. So if you had a private cluster deployment, it should work now.
https://hub.helm.sh/charts/aerospike/aerospike-enterprise

I'll close this issue now, but feel free to reopen it if you are stuck or have any questions.
