### ISSUE TITLE
tolerations support?

### ISSUE THREAD

**Issue by exherb** [aerospike/aerospike-kubernetes-enterprise#20]
https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/

**Comment by spkesan** [comment]
@exherb 
Pod `tolerations` for node `taints` are supported in the latest release - [Aerospike Helm Chart v1.4.0](https://github.com/aerospike/aerospike-kubernetes-enterprise/releases/tag/1.4.0)
Helm Hub - [aerospike/aerospike-enterprise](https://hub.helm.sh/charts/aerospike/aerospike-enterprise)
