### ISSUE TITLE
livenessProbe should be configurable

### ISSUE THREAD

**Issue by exherb** [aerospike/aerospike-kubernetes-enterprise#24]
startup speed is very slow when we got lots of objects (about 16~30 m)

**Comment by spkesan** [comment]
Thanks @exherb for reporting this. It makes sense to allow `livenessProbe` and `readinessProbe` configurable.
I have made the respective changes to `master` and it should be part of next helm chart release.
In the meantime, you can use the chart from [`master`](https://github.com/aerospike/aerospike-kubernetes-enterprise/tree/master/helm)

```
helm install test-release aerospike/aerospike-enterprise --set livenessProbe.initialDelaySeconds=120 --set readinessProbe.initialDelaySeconds=120   ..........
```
